#friends=['jonathan', 'evans','crispo','yustina','lucy']
#print( "My name is " + friends[3].title())

#bykes=['boxer','tvs','captain','honda','tiger','sonlink']
#print( f"The best {bykes[4].title()} Spareparts are found in Nairobi")
#bykes[0]='dukati'
#bykes.append('boxer')
#bykes.insert(1,'dt')
#print(bykes)

#states=[]
#states.append('Tharakanithi')
#states.append('Meru')
#states.append('Nyeri')
#states.append('nairobi')
#states.append('mombasa')
#states.append('kirinyaga')
#cars=['axio','belta','honda','fit','vitz','subaru','mazda']
#cars.insert(0,'dukati')
#firstcar=cars.pop(1)
#print (cars)
#print( f"My first car to own was {firstcar.upper()}")
#cars.remove('vitz')
#print(cars)
dinner=['evans','yustina','crispo','fox','ben','ann']
print (f"Hello {dinner[0].title()} Welcome to dinner ")
print("Hello" + dinner [1].title() + " Welcome to dinner")
print(f"Hello {dinner[2].title()} Welcome to dinner")
print("Hello"+dinner[3].title()+" Welcome to dinner")
print(f"Hello {dinner[4].title()} Welcome to dinner")
print("Hello"+dinner[-1].title()+"Welcome to supper")
print(f"Hello {dinner[0].title()} Will not make it ")
dinner.insert(0,'Susan')
dinner.insert(-1,'frenzy')
print(dinner)
dinner.pop()
print(dinner)
dinner.pop(1)
print (dinner)
dinner.pop(-4)
print(dinner)
dinner.insert(4,'mary')
print (dinner)
dinner.insert(0,'kariuki')
print(dinner)
dinner.insert(3,'riungu')
print(dinner)
dinner.append('justo')
print(dinner) 
print('I will only invite two guests')
guest=dinner.pop()
print(dinner)
guest1=dinner.pop(1)
print(dinner)
del dinner[1]
print(f"Sorry I cant invite you {guest1.title()}")
